#import <Foundation/Foundation.h>
@interface PodsDummy_Pods_AssignmentDisplayProductDataAPI_AssignmentDisplayProductDataAPIUITests : NSObject
@end
@implementation PodsDummy_Pods_AssignmentDisplayProductDataAPI_AssignmentDisplayProductDataAPIUITests
@end
